import Header from "@/components/Common/Header";
import "./globals.scss";
import { Montserrat } from "next/font/google";
import BottomNav from "@/components/Common/BottomNav";

const inter = Montserrat({ subsets: ["latin"] });

export const metadata = {
  title: "Ats Dashboard",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <Header />
        {children}

        <BottomNav />
      </body>
    </html>
  );
}
