import Header from '@/components/Common/Header';
import './globals.scss';
import { Montserrat } from 'next/font/google';
import BottomNav from '@/components/Common/BottomNav';
import Navbar from '@/components/Common/Navbar';

const inter = Montserrat({ subsets: ['latin'] });

export const metadata = {
  title: 'Ats Dashboard',
  description: 'Generated by create next app'
};

export default function RootLayout({
  children
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={`${inter.className} laptop:bg-grey50`}>
        <Header />
        <Navbar customClass={'mt-7'} />
        <div className="laptop:ml-[15.3125rem]">{children}</div>

        <BottomNav />
      </body>
    </html>
  );
}
